apiVersion: apps/v1
kind: Deployment
metadata:
  name: capgimini-webapp
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: capgimini-webapp
  template:
    metadata:
      labels:
        app: capgimini-webapp
    spec:
      containers:
      - image: hello-world
        name: capgimini-webapp
        ports:
        - containerPort: 82
